### ISSUE TITLE
Revised Critical Hit Aversion fails on M#PIRBAN (pirate bandanna) from Amber NPC mod

### ISSUE THREAD

**Issue by agb1** [Gibberlings3/ItemRevisions#11]
Install error observed by zonx and Quiet on SHS.  Game type is BG2EE.

Installing [Revised Critical Hit Aversion] [V4 8 Beta]
Copying and patching 4246 files ...
ERROR: [M#PIRBAN.ITM] -> [override/M#PIRBAN.ITM] Patching Failed (COPY) (Invalid_argument("Str.search_forward"))
Stopping installation because of error.
ERROR Installing [Revised Critical Hit Aversion], rolling back to previous state
Will uninstall 66 files for [ITEM_REV/ITEM_REV.TP2] component 1200.
Uninstalled 66 files for [ITEM_REV/ITEM_REV.TP2] component 1200.
ERROR: Invalid_argument("Str.search_forward")
Please submit a report regarding this problem, including the information contained in SETUP-ITEM_REV.DEBUG to Demivrgvs, Ardanis and Mike1072 at forums.gibberlings3.net
Automatically Skipping [Revised Critical Hit Aversion] because of error.

Original item file is attached to SHS thread in zip along with biffed final copy from zonx's install (modified by Might and Guile #120 ... but Quiet reported the same error also occurs without Might and Guile, i.e., with original file, as no other mods patched it):

http://www.shsforums.net/topic/56670-big-world-setup-an-attempt-to-update-the-program/?p=584754

**Comment by mike1072** [comment]
I can't replicate the install error with either file.

However, IR does think this item is a helmet.  We use the animation of the item to help determine whether it's an actual helmet or some other type of headgear.  The normal way to specify that an item has no animation is to set the animation string to "&nbsp;&nbsp;" (two spaces), but this particular file uses the null string instead.  We try to account for that in the code, but we didn't do it right (we compare the value we read from the file to the empty string, but the way we read it, the value we get is actually a string of two nulls).

I will post a modified version of the component in the SHS thread to see if this solves the problem the player is having installing the mod.

**Comment by mike1072** [comment]
The problem was reported solved, so I've committed the fix.
